---
- name: repo server
  hosts: localhost
  vars:
  tasks:
    - name: install httpd server
      dnf:
        name: httpd
        state: present
    - name: start httpd server
      service:
        name: httpd
        state: started
        enabled: yes
    - name: open httpd firewall service, need ansible posix
      firewalld:
        service: httpd
        permanent: true
        state: enabled
        
    - name: create repo direcotires
      file: 
        path: /reposerve
        state: directory
    - name: create a symbolic link
      file:
        src: /reposerver
        dest: /var/www/html/reposerver
        state: link


        
    
  
  
