---
- name: DNS for secure server
  hosts: dev test servers
  tasks:
    - name: run dns template
      template:
        src: dns.j2
        dest: /etc/hosts
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

