---
- name: deploy an nginx webserver
  hosts: test
  tasks:
    - name: docker dependencies 
      apt:
        name: python3-docker
        state: present
    - name: docker repo
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
    - name: pull nginx image
      community.docker.docker_image:
        name: nginx:latest
        source: pull
    - name: run nginx container
      community.docker.docker_container:
        name: nginx_web
        image: nginx:latest
        ports:
          - "8082:80"
          - "444:443"
        restart_policy: always
        volumes:
          - /home/ansible/twosloo/index.html:/usr/share/nginx/html/index.html
