---
- name: deploy an nginx webserver
  hosts: test
  tasks:
    - name: pull nginx image
      community.docker.docker_image:
        name: nginx:latest
        source: pull
    - name: run nginx container
      community.docker.docker_container:
        name: nginx_web
        image: nginx:latest
        ports:
          - "8082:80"
          - "444:443"
        restart_policy: always
        volumes:
          - /home/ansible/twosloo/index.html:/usr/share/nginx/html/index.html
