---
- name: Update and upgrade systems
  hosts: all
  become: yes  # Run tasks with root privileges

  tasks:
    - name: Update and upgrade Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Update and upgrade RHEL/CentOS systems
      dnf:
        name: '*'
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
