- name: create user with encrypted password
  hosts: ansible1
  vars_prompt:
    - name: usernames
      prompt: What is your username?
      private: false
    - name: password
      prompt: What is your password?
      private: true
      encrypt: sha512_crypt
      confirm: true
      salt_size: 7
  tasks:
    - name: create the user
      user:
        name: "{{ usernames }}"
        password: "{{ password }}"
        shell: /bin/bash

    
